# Generated by Django 3.2.4 on 2021-07-21 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration_app', '0002_free_session_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='free_session_registration',
            name='time_slot',
        ),
    ]
