# Generated by Django 3.2.4 on 2021-07-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration_app', '0003_remove_free_session_registration_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='free_session_registration',
            name='time_slot',
            field=models.DateTimeField(default=None),
        ),
    ]
