# Generated by Django 3.2.4 on 2021-07-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration_app', '0004_free_session_registration_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='free_session_registration',
            name='time_slot',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
